#! /bin/sh
### BEGIN INIT INFO
# Provides:          initafterreboot
### END INIT INFO
PATH=/sbin:/bin:/usr/sbin:/usr/bin
case "$1" in
    start)
        /root/ecs.sh
        ;;
    stop|restart|reload)
        ;;
esac